global:
  scrape_interval: 1s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

scrape_configs:
  - job_name: 'cpu-exporter'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['cpu-exporter:9900']

rule_files:
  - 'rules/1.basic.yml'
  #- 'rules/2.absent.yml'
  #- 'rules/3.group.yml'
  #- 'rules/4.templating.yml'
  # restart prometheus
